In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
import pandas as pd

DATA = '/content/drive/MyDrive/DataSets'
RAW = f'{DATA}/raw'

In [ ]:
# Load sample month from shared folder
df_2024 = pd.read_csv(f'{RAW}/2024/bikeshare-ridership-2024-01_Jan.csv')
df_2024.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,26682740,528,7041,2024-01-01 00:00:08,Edward St / Yonge St,7130.0,2024-01-01 00:08:56,Davenport Rd / Bedford Rd,7855,Casual,EFIT G5
1,26682742,1924,7245,2024-01-01 00:02:04,Tecumseth St / Queen St W - SMART,7259.0,2024-01-01 00:34:08,Lower Spadina Ave / Lake Shore Blvd W,2453,Casual,ICONIC
2,26682743,2741,7052,2024-01-01 00:03:25,Wellington St W / Bay St,7366.0,2024-01-01 00:49:06,Fort York Blvd / Bathurst St - SMART,7332,Member,ICONIC
3,26682744,353,7041,2024-01-01 00:03:39,Edward St / Yonge St,7418.0,2024-01-01 00:09:32,College Park - Yonge St Entrance,782,Member,ICONIC
4,26682746,2118,7721,2024-01-01 00:04:44,Widmer St / King St W,7721.0,2024-01-01 00:40:02,Widmer St / King St W,1008,Member,ICONIC

In [ ]:
df_2023 = pd.read_csv(f'{RAW}/2023/Bike share ridership 2023-01.csv')
df_2023.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,20148784,840,7022,01/01/2023 00:00,Simcoe St / Queen St W,7703.0,01/01/2023 00:14,NaN,1770,Casual Member
1,20148785,722,7399,01/01/2023 00:01,Lower Jarvis / Queens Quay E,7533.0,01/01/2023 00:13,Housey St / Dan Leckie Way,6400,Casual Member
2,20148786,1054,7269,01/01/2023 00:02,Toronto Eaton Centre (Yonge St),7076.0,01/01/2023 00:20,York St / Queens Quay W,4068,Annual Member
3,20148790,1329,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,427,Casual Member
4,20148791,1291,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,1840,Casual Member

For each month:
shape, column names, dtypes, head

In [ ]:
df_2024.shape, df_2023.shape

((204879, 11), (180135, 10))

In [ ]:
df_2024.columns, df_2023.columns

(Index(['Trip_Id', 'Trip_Duration', 'Start_Station_Id', 'Start_Time',
        'Start_Station_Name', 'End_Station_Id', 'End_Time', 'End_Station_Name',
        'Bike_Id', 'User_Type', 'Bike_Model'],
       dtype='object'),
 Index(['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time',
        'Start Station Name', 'End Station Id', 'End Time', 'End Station Name',
        'Bike Id', 'User Type'],
       dtype='object'))

In [ ]:
df_2024.dtypes, df_2023.dtypes

(Trip_Id                 int64
 Trip_Duration           int64
 Start_Station_Id        int64
 Start_Time             object
 Start_Station_Name     object
 End_Station_Id        float64
 End_Time               object
 End_Station_Name       object
 Bike_Id                 int64
 User_Type              object
 Bike_Model             object
 dtype: object,
 Trip Id                 int64
 Trip  Duration          int64
 Start Station Id        int64
 Start Time             object
 Start Station Name     object
 End Station Id        float64
 End Time               object
 End Station Name       object
 Bike Id                 int64
 User Type              object
 dtype: object)

Check differences in the column names

In [ ]:
df_2024.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,26682740,528,7041,2024-01-01 00:00:08,Edward St / Yonge St,7130.0,2024-01-01 00:08:56,Davenport Rd / Bedford Rd,7855,Casual,EFIT G5
1,26682742,1924,7245,2024-01-01 00:02:04,Tecumseth St / Queen St W - SMART,7259.0,2024-01-01 00:34:08,Lower Spadina Ave / Lake Shore Blvd W,2453,Casual,ICONIC
2,26682743,2741,7052,2024-01-01 00:03:25,Wellington St W / Bay St,7366.0,2024-01-01 00:49:06,Fort York Blvd / Bathurst St - SMART,7332,Member,ICONIC
3,26682744,353,7041,2024-01-01 00:03:39,Edward St / Yonge St,7418.0,2024-01-01 00:09:32,College Park - Yonge St Entrance,782,Member,ICONIC
4,26682746,2118,7721,2024-01-01 00:04:44,Widmer St / King St W,7721.0,2024-01-01 00:40:02,Widmer St / King St W,1008,Member,ICONIC

In [ ]:
df_2023.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,20148784,840,7022,01/01/2023 00:00,Simcoe St / Queen St W,7703.0,01/01/2023 00:14,NaN,1770,Casual Member
1,20148785,722,7399,01/01/2023 00:01,Lower Jarvis / Queens Quay E,7533.0,01/01/2023 00:13,Housey St / Dan Leckie Way,6400,Casual Member
2,20148786,1054,7269,01/01/2023 00:02,Toronto Eaton Centre (Yonge St),7076.0,01/01/2023 00:20,York St / Queens Quay W,4068,Annual Member
3,20148790,1329,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,427,Casual Member
4,20148791,1291,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,1840,Casual Member

Compare how the same field is written across years: date format, how missing values appear, how station IDs are typed, what the user type labels are, what Bike_Model values exist.

Check that each file's Start_Time range matches the month in its filename.

Standardize the column names set the group will use from here on, and the mapping from each year's
names to it

In [3]:
df_2025 = pd.read_csv(f'{RAW}/2025/bikeshare_2025_01.csv')
df_2025.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,34637659,193,7192,2025-01-01 00:02:15,Harbord St / Clinton St,7155.0,2025-01-01 00:05:28,Harbord St / Clinton St,4422,Member,ICONIC
1,34637678,464,7508,2025-01-01 00:14:07,Berkeley St / Dundas St E - SMART,7042.0,2025-01-01 00:21:51,Berkeley St / Dundas St E - SMART,4618,Member,ICONIC
2,34637663,770,7094,2025-01-01 00:07:21,14 Arundel Ave,7777.0,2025-01-01 00:20:11,14 Arundel Ave,7975,Member,EFIT G5
3,34637679,559,7032,2025-01-01 00:14:09,Augusta Ave / Dundas St W,7541.0,2025-01-01 00:23:28,Augusta Ave / Dundas St W,3179,Member,ICONIC
4,34637658,116,7017,2025-01-01 00:02:13,Widmer St / Adelaide St W - SMART,7102.0,2025-01-01 00:04:09,Widmer St / Adelaide St W - SMART,3177,Member,ICONIC

In [4]:
df_2025.shape

(202946, 11)

In [7]:
df_2025.isnull().sum()

Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        135
End_Time               26
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64

Jan 2025 missing values: End_Station_Id has 135 missing, End_Time has 26 missing. All other columns are complete.

In [8]:
df_2025['Trip_Duration'].describe()

count    202946.000000
mean        675.672051
std         916.891746
min           0.000000
25%         350.000000
50%         543.000000
75%         831.000000
max       85506.000000
Name: Trip_Duration, dtype: float64

In [9]:
(df_2025['Trip_Duration'] < 60).sum()

np.int64(512)

In [10]:
(df_2025['Trip_Duration'] > 21600).sum()

np.int64(45)

Jan 2025 trip duration: Min is 0 seconds and max is 85,506 seconds (about 23.75 hours). 512 trips are shorter than 60 seconds. 45 trips are longer than 6 hours. Nothing removed.

In [11]:
(df_2025['Start_Station_Id'] == df_2025['End_Station_Id']).sum()

np.int64(2990)

Jan 2025 same start and end station: 2,990 trips start and end at the same station ID. Nothing removed.

In [12]:
df_2025['Start_Time'].min(), df_2025['Start_Time'].max()

('2025-01-01 00:01:51', '2025-01-31 23:59:15')

Jan 2025 date range: Start_Time goes from 2025-01-01 to 2025-01-31. All trips start inside January.

In [20]:
def check_month(path):
    df = pd.read_csv(path)
    print(path)
    print('Shape:', df.shape)
    print('Missing values:')
    print(df.isnull().sum())
    print('Trips under 60 sec:', (df['Trip_Duration'] < 60).sum())
    print('Trips over 6 hours:', (df['Trip_Duration'] > 21600).sum())
    print('Same start/end station:', (df['Start_Station_Id'] == df['End_Station_Id']).sum())
    print('Date range:', df['Start_Time'].min(), df['Start_Time'].max())

In [21]:
check_month(f'{RAW}/2025/bikeshare_2025_01.csv')

/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_01.csv
Shape: (202946, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        135
End_Time               26
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 512
Trips over 6 hours: 45
Same start/end station: 2990
Date range: 2025-01-01 00:01:51 2025-01-31 23:59:15

In [22]:
for m in range(1, 13):
    month = str(m).zfill(2)
    check_month(f'{RAW}/2025/bikeshare_2025_{month}.csv')
    print('-' * 40)

/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_01.csv
Shape: (202946, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        135
End_Time               26
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 512
Trips over 6 hours: 45
Same start/end station: 2990
Date range: 2025-01-01 00:01:51 2025-01-31 23:59:15
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_02.csv
Shape: (125670, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        302
End_Time               44
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 605
Trips over 6 hours: 67
Same start/end station: 2138
Date range: 2025-02-01 00:00:20 2025-02-28 23:59:14
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_03.csv
Shape: (312178, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        223
End_Time               62
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 688
Trips over 6 hours: 96
Same start/end station: 5297
Date range: 2025-03-01 00:00:16 2025-03-31 23:59:22
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_04.csv
Shape: (471525, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        331
End_Time               76
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 1084
Trips over 6 hours: 190
Same start/end station: 12300
Date range: 2025-04-01 00:00:25 2025-04-30 23:59:58
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_05.csv
Shape: (699461, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        509
End_Time              107
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 1352
Trips over 6 hours: 345
Same start/end station: 23929
Date range: 2025-05-01 00:00:02 2025-05-31 23:59:55
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_06.csv
Shape: (980624, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        830
End_Time              130
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 2426
Trips over 6 hours: 595
Same start/end station: 42604
Date range: 2025-06-01 00:00:15 2025-06-30 23:59:53
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_07.csv
Shape: (1192062, 11)
Missing values:
Trip_Id                  0
Trip_Duration            0
Start_Station_Id         0
Start_Time               0
Start_Station_Name       0
End_Station_Id        1029
End_Time               135
End_Station_Name         0
Bike_Id                  0
User_Type                0
Bike_Model               0
dtype: int64
Trips under 60 sec: 2304
Trips over 6 hours: 648
Same start/end station: 50225
Date range: 2025-07-01 00:00:00 2025-07-31 23:59:59
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_08.csv
Shape: (1164697, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        841
End_Time              133
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 1937
Trips over 6 hours: 638
Same start/end station: 47066
Date range: 2025-08-01 00:00:00 2025-08-31 23:59:53
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_09.csv
Shape: (1062001, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        7
Start_Time              0
Start_Station_Name      7
End_Station_Id        818
End_Time              124
End_Station_Name        7
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 2046
Trips over 6 hours: 479
Same start/end station: 32043
Date range: 2025-09-01 00:00:03 2025-09-30 23:59:46
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_10.csv
Shape: (872482, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        826
End_Time              107
End_Station_Name        0
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 2911
Trips over 6 hours: 394
Same start/end station: 19269
Date range: 2025-10-01 00:00:32 2025-10-31 23:59:59
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_11.csv
Shape: (511934, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        528
End_Time               93
End_Station_Name      528
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 2170
Trips over 6 hours: 227
Same start/end station: 6519
Date range: 2025-11-01 00:00:01 2025-11-30 23:59:46
----------------------------------------
/content/drive/MyDrive/DataSets/raw/2025/bikeshare_2025_12.csv
Shape: (216940, 11)
Missing values:
Trip_Id                 0
Trip_Duration           0
Start_Station_Id        0
Start_Time              0
Start_Station_Name      0
End_Station_Id        389
End_Time               55
End_Station_Name      389
Bike_Id                 0
User_Type               0
Bike_Model              0
dtype: int64
Trips under 60 sec: 1878
Trips over 6 hours: 75
Same start/end station: 2858
Date range: 2025-12-01 00:00:37 2025-12-31 23:59:49
----------------------------------------

In [23]:
rows = []
for m in range(1, 13):
    month = str(m).zfill(2)
    df = pd.read_csv(f'{RAW}/2025/bikeshare_2025_{month}.csv')
    rows.append({
        'month': month,
        'trips': len(df),
        'missing_end_id': df['End_Station_Id'].isnull().sum(),
        'missing_end_time': df['End_Time'].isnull().sum(),
        'under_60s': (df['Trip_Duration'] < 60).sum(),
        'over_6h': (df['Trip_Duration'] > 21600).sum(),
        'same_station': (df['Start_Station_Id'] == df['End_Station_Id']).sum(),
        'first_trip': df['Start_Time'].min(),
        'last_trip': df['Start_Time'].max(),
    })
summary_2025 = pd.DataFrame(rows)
summary_2025

,month,trips,missing_end_id,missing_end_time,under_60s,over_6h,same_station,first_trip,last_trip
0,01,202946,135,26,512,45,2990,2025-01-01 00:01:51,2025-01-31 23:59:15
1,02,125670,302,44,605,67,2138,2025-02-01 00:00:20,2025-02-28 23:59:14
2,03,312178,223,62,688,96,5297,2025-03-01 00:00:16,2025-03-31 23:59:22
3,04,471525,331,76,1084,190,12300,2025-04-01 00:00:25,2025-04-30 23:59:58
4,05,699461,509,107,1352,345,23929,2025-05-01 00:00:02,2025-05-31 23:59:55
5,06,980624,830,130,2426,595,42604,2025-06-01 00:00:15,2025-06-30 23:59:53
6,07,1192062,1029,135,2304,648,50225,2025-07-01 00:00:00,2025-07-31 23:59:59
7,08,1164697,841,133,1937,638,47066,2025-08-01 00:00:00,2025-08-31 23:59:53
8,09,1062001,818,124,2046,479,32043,2025-09-01 00:00:03,2025-09-30 23:59:46
9,10,872482,826,107,2911,394,19269,2025-10-01 00:00:32,2025-10-31 23:59:59
10,11,511934,528,93,2170,227,6519,2025-11-01 00:00:01,2025-11-30 23:59:46
11,12,216940,389,55,1878,75,2858,2025-12-01 00:00:37,2025-12-31 23:59:49

2025 summary (all 12 months):

1. The month with the most trips under 60 seconds is October (2,911 trips). It is not the busiest month.
2. Missing values are only in End_Station_Id and End_Time. In September (7), November (528) and December (389), End_Station_Name is also missing.
3. All dates stay inside their own month. Nothing removed.

In [24]:
for m in range(1, 13):
    month = str(m).zfill(2)
    df = pd.read_csv(f'{RAW}/2025/bikeshare_2025_{month}.csv')
    print(month, df['End_Station_Name'].isnull().sum())

01 0
02 0
03 0
04 0
05 0
06 0
07 0
08 0
09 7
10 0
11 528
12 389

In [26]:
summary_2025.to_csv(f'{DATA}/summary_2025.csv', index=False)