<a href="https://colab.research.google.com/github/karquiza/bikeshare-toronto-demand/blob/main/notebooks/00_explore_by_months.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

DATA = '/content/drive/MyDrive/DataSets'
RAW = f'{DATA}/raw'

In [6]:
# Load sample month from shared folder
df_2024 = pd.read_csv(f'{RAW}/2024/bikeshare-ridership-2024-01_Jan.csv')
df_2024.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,26682740,528,7041,2024-01-01 00:00:08,Edward St / Yonge St,7130.0,2024-01-01 00:08:56,Davenport Rd / Bedford Rd,7855,Casual,EFIT G5
1,26682742,1924,7245,2024-01-01 00:02:04,Tecumseth St / Queen St W - SMART,7259.0,2024-01-01 00:34:08,Lower Spadina Ave / Lake Shore Blvd W,2453,Casual,ICONIC
2,26682743,2741,7052,2024-01-01 00:03:25,Wellington St W / Bay St,7366.0,2024-01-01 00:49:06,Fort York Blvd / Bathurst St - SMART,7332,Member,ICONIC
3,26682744,353,7041,2024-01-01 00:03:39,Edward St / Yonge St,7418.0,2024-01-01 00:09:32,College Park - Yonge St Entrance,782,Member,ICONIC
4,26682746,2118,7721,2024-01-01 00:04:44,Widmer St / King St W,7721.0,2024-01-01 00:40:02,Widmer St / King St W,1008,Member,ICONIC

In [7]:
df_2023 = pd.read_csv(f'{RAW}/2023/Bike share ridership 2023-01.csv')
df_2023.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,20148784,840,7022,01/01/2023 00:00,Simcoe St / Queen St W,7703.0,01/01/2023 00:14,NaN,1770,Casual Member
1,20148785,722,7399,01/01/2023 00:01,Lower Jarvis / Queens Quay E,7533.0,01/01/2023 00:13,Housey St / Dan Leckie Way,6400,Casual Member
2,20148786,1054,7269,01/01/2023 00:02,Toronto Eaton Centre (Yonge St),7076.0,01/01/2023 00:20,York St / Queens Quay W,4068,Annual Member
3,20148790,1329,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,427,Casual Member
4,20148791,1291,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,1840,Casual Member

For each month:
shape, column names, dtypes, head

In [9]:
df_2024.shape, df_2023.shape

((204879, 11), (180135, 10))

In [10]:
df_2024.columns, df_2023.columns

(Index(['Trip_Id', 'Trip_Duration', 'Start_Station_Id', 'Start_Time',
        'Start_Station_Name', 'End_Station_Id', 'End_Time', 'End_Station_Name',
        'Bike_Id', 'User_Type', 'Bike_Model'],
       dtype='object'),
 Index(['Trip Id', 'Trip  Duration', 'Start Station Id', 'Start Time',
        'Start Station Name', 'End Station Id', 'End Time', 'End Station Name',
        'Bike Id', 'User Type'],
       dtype='object'))

In [11]:
df_2024.dtypes, df_2023.dtypes

(Trip_Id                 int64
 Trip_Duration           int64
 Start_Station_Id        int64
 Start_Time             object
 Start_Station_Name     object
 End_Station_Id        float64
 End_Time               object
 End_Station_Name       object
 Bike_Id                 int64
 User_Type              object
 Bike_Model             object
 dtype: object,
 Trip Id                 int64
 Trip  Duration          int64
 Start Station Id        int64
 Start Time             object
 Start Station Name     object
 End Station Id        float64
 End Time               object
 End Station Name       object
 Bike Id                 int64
 User Type              object
 dtype: object)

Check differences in the column names

In [12]:
df_2024.head()

,Trip_Id,Trip_Duration,Start_Station_Id,Start_Time,Start_Station_Name,End_Station_Id,End_Time,End_Station_Name,Bike_Id,User_Type,Bike_Model
0,26682740,528,7041,2024-01-01 00:00:08,Edward St / Yonge St,7130.0,2024-01-01 00:08:56,Davenport Rd / Bedford Rd,7855,Casual,EFIT G5
1,26682742,1924,7245,2024-01-01 00:02:04,Tecumseth St / Queen St W - SMART,7259.0,2024-01-01 00:34:08,Lower Spadina Ave / Lake Shore Blvd W,2453,Casual,ICONIC
2,26682743,2741,7052,2024-01-01 00:03:25,Wellington St W / Bay St,7366.0,2024-01-01 00:49:06,Fort York Blvd / Bathurst St - SMART,7332,Member,ICONIC
3,26682744,353,7041,2024-01-01 00:03:39,Edward St / Yonge St,7418.0,2024-01-01 00:09:32,College Park - Yonge St Entrance,782,Member,ICONIC
4,26682746,2118,7721,2024-01-01 00:04:44,Widmer St / King St W,7721.0,2024-01-01 00:40:02,Widmer St / King St W,1008,Member,ICONIC

In [13]:
df_2023.head()

,Trip Id,Trip Duration,Start Station Id,Start Time,Start Station Name,End Station Id,End Time,End Station Name,Bike Id,User Type
0,20148784,840,7022,01/01/2023 00:00,Simcoe St / Queen St W,7703.0,01/01/2023 00:14,NaN,1770,Casual Member
1,20148785,722,7399,01/01/2023 00:01,Lower Jarvis / Queens Quay E,7533.0,01/01/2023 00:13,Housey St / Dan Leckie Way,6400,Casual Member
2,20148786,1054,7269,01/01/2023 00:02,Toronto Eaton Centre (Yonge St),7076.0,01/01/2023 00:20,York St / Queens Quay W,4068,Annual Member
3,20148790,1329,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,427,Casual Member
4,20148791,1291,7721,01/01/2023 00:04,NaN,7685.0,01/01/2023 00:26,NaN,1840,Casual Member

Compare how the same field is written across years: date format, how missing values appear, how station IDs are typed, what the user type labels are, what Bike_Model values exist.

Check that each file's Start_Time range matches the month in its filename.

Standardize the column names set the group will use from here on, and the mapping from each year's
names to it